import "./../layout.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <div className={"nested-layout"}>{children}</div>;
}
